---
title: "The impact of the pandemic and subsequent policies on parkrun participation in England: 2010 to 2023"
format: html
editor: visual
---

## Abstract

Background:

parkrun is a free weekly timed 5k running event held in X locations worldwide, with over Y locations in England. It is widely cited as an example of a public health success story, increasing physical activity in many inactive people. Previous work analysed the growth in participation in parkrun in different socioeconomic groups in society from 2010 to 2019, showing that rates of participation are lower in more deprived communities, despite equitable geographic access. This paper aims to extend this analysis to 2023, and to investigate the impact of the coronavirus pandemic on participation in parkrun in England.

Methods:

We utilise the same methods described in Smith et al. 2021 to investigate the trends in parkrun participation across approximately 20 million event-LSOA combinations across England. We report the changes in participation (finishers per 1,000 residents) and access (geodesic access to nearest parkrun event) by quintile of IMD for each month between January 2020 and February 2023. We also undertake interrupted time series analysis to estimate the effect of the coronavirus pandemic and its related policies on parkrun participation, estimating the impact of this shock on the level and rate of growth of parkrun. We report an estimate of the number of runs lost due to the pandemic and associated policy, and discuss the potential health implications of this.

Results:

parkrun experienced a significant (X%) reduction in the number of runners from xxxx to xxxx. This effect was largest in the least deprived communities, which remain (as of XXXX) XX% of the peak participation prior to the pandemic. The rate at which parkrun was growing also decreased, from around Y% in 2020 to around W% in 2022. The combination of these two effects (step change and slope change) results in an estimate that YYYY runs were lost due to changes in behavior and regulation during the pandemic.

Discussion:

parkrun was not immune to the pandemic. Our analysis shows that participation in parkrun decreased prior to changes in policy that culminated in 'lockdowns', likely due to individual preferences around risk-taking. The overall impact of the pandemic and related policy on parkrun was stark, with a significant decrease in both participation rates and the rate of growth in engagement in the event. This has long term implications for the healthcare system, via diseases correlated with physical inactivity including type 2 diabetes, cardiovascular events, numerous cancers and mental health. It also has implications for local communities which have benefited from improvements in social capital brought about by volunteers and networks formed around parkrun. Policymakers may want to consider the tradeoff between the benefits of any reduction in transmission of an infectious disease in outdoor physical activity settings and the negative consequences of reduction in general population physical actiivty associated with the same policies. Further research should be able to estimate this across a single dimension (e.g. Quality Adjusted Life Years), even if conducting a multi-criteria decision analysis is unfeasible or undesirable.

Conclusion:

parkrun was severely affected by the pandemic and associated societal response. This resulted in a reduction in both the level of and growth in participation in the 5k running events, likely decreasing population physical activity and therefore increasing physical-inactivity associated disease burden over the next decade.

## Introduction

## Methods

## Results

## Discussion

## Conclusion
